### ISSUE TITLE
Senior members unable to sign up for team events

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#119]
**Describe the bug**
Senior members not on team list cannot sign up for team events

**To Reproduce**
1. Su as senior member
2. Go to team event
3. See "Cannot sign up for event: Member is required to be a part of the team" message displayed

**Expected behavior**
Senior members (or at least ones holding a staff or senior staff position) should be able to sign up for team events regardless of team membership.

**Comment by r-a303931** [comment]
This uncovered a bug where no one was able to sign up for events when the 'Limit sign ups to team members' checkbox was unchecked. This issue specifically is resolved by the attendance multi-add page, where an event organizer can add the senior members regardless of team membership.
