### ISSUE TITLE
Include SMTP server container

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#146]
**Is your feature request related to a problem? Please describe.**
Current mailer relies on Amazon Web Services (AWS) Simple Email Service (SES) send capability.

**Describe the solution you'd like**
It may be prudent to include full SMTP server capability in-house and remove reliability on external service.

**Describe alternatives you've considered**
Continue to use SES, use raspberry Pi

**Comment by r-a303931** [comment]
SES will continue over until UnitPlanner, which will use Microsoft GRAPH API to interact with Outlook
