### ISSUE TITLE
Implement retention products

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#152]
**Is your feature request related to a problem? Please describe.**
Membership levels can be tracked over time but current products only provide a snapshot of status.

**Describe the solution you'd like**
Use historical CAPWATCH download data to provide unit membership levels to recruiting & retention staff

**Comment by r-a303931** [comment]
Definitely move to UnitPlanner, as this would require an architecture shift in how we manage table content for CAPWATCH.
