### ISSUE TITLE
Event Pages

### ISSUE THREAD

**Issue by r-a303931** [cap-md089/evmplus-v6#18]
**Is your feature request related to a problem? Please describe.**
Currently, all events are grouped together. It can be hard to discover events when someone is interested in events associated with a specific program, for instance a team or something more abstract like Emergency Services.

**Describe the solution you'd like**
Ideally, there would be a way to group these events according to team or another arbitrary system that can be set up by a site admin; for instance, the current Maryland Wing web page has functional groups and event information grouped on those pages.

**Additional context**
[MDWG A3 page, which shows emergency services events](http://mdwg.cap.gov/index.php/a3-operations/)

**Comment by grioux-neo** [comment]
How about implementing tags for events?  Then filters could be applied to list only events with that tag?  Events could have more than one tag.

**Comment by r-a303931** [comment]
Move to UnitPlanner

> How about implementing tags for events? Then filters could be applied to list only events with that tag? Events could have more than one tag.

I was thinking about providing a mix of dynamic and static content, for pages like this: https://mdwg.cap.gov/staff-sections/emergency-services

We could provide a page editor which allows for blocks, and one block can be a text block another block can be a 'list of recent events with a specified tag or team'
