### ISSUE TITLE
Descriptive account process feedback

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#226]
**Is your feature request related to a problem? Please describe.**
Error messages, while technically accurate, do not indicate the specific error source nor an avenue in which to overcome the error.

**Describe the solution you'd like**
Update action descriptions and error message descriptions associated with account creation, username refresh, and password reset functions to include exhaustively descriptive comments and process steps.

**Describe alternatives you've considered**
Continue to field repeated help requests and provide the same responses of "check your spam folder", "the link has expired", "you must use an email address in eServices", etc.

**Additional context**
Continuing to respond to user requests detracts from time available to dedicate to system development and improvement.

**Comment by r-a303931** [comment]
Which error messages where? Can you provide a list of actions that you are looking for, or do you want to go over every error message?

**Comment by grioux-neo** [comment]
I added a few. Good enough for now.  Pull request initiated.
