### ISSUE TITLE
Find member does not include all appropriate members in results

### ISSUE THREAD

**Issue by r-a303931** [cap-md089/evmplus-v6#320]
**Describe the bug**
When using the echelon find member feature, only members who hold duty positions are included in the search results

**To Reproduce**
1. Go to echelon admin dashboard
2. Click on 'Find Member'
3. Search for cadet

**Expected behavior**
The cadet that is searched for should appear

**Actual behavior**
No cadets appear in the search results

**Comment by grioux-neo** [comment]
Need to look at lines 90-180 in packages/server/src/api/member/membersearch.ts
SQL query is sufficient to pull appropriate data.  Somewhere in the javascript, members who do not hold duty positions are filtered out.
