### ISSUE TITLE
Align Cadet Grade Abbreviations with CAP Style Guide

### ISSUE THREAD

**Issue by dtrick-CAP** [cap-md089/evmplus-v6#372]
Specifically:
- Cadet Second Lieutenant should display as "C/2d Lt"
- Cadet First Lieutenant should display as "C/1st Lt"
- Cadet Lieutenant Colonel should display as "C/Lt Col"

Source for branding: https://civilairpatrol.frontify.com/d/crhrf1Aw1Ci9/style-guide#/styles/grade-rank-abbreviations-punctuation

**Comment by grioux-neo** [comment]
CAPWATCH data indicate cadet grades out of alignment with CAP style guide.  Event Manager displays CAPWATCH data.  Helpdesk ticket #87583
