### ISSUE TITLE
Implement Color Coding of the Email List based on Membership Expiration Date

### ISSUE THREAD

**Issue by dtrick-CAP** [cap-md089/evmplus-v6#376]
A feature of a previous version of Event Manager was the color coding of the email selector based on membership expiration date. Members who were within 30 days of expiration were highlighted orange and members who had expired were highlighted Red until their membership disappeared from CAPWATCH 90 days after expiration.

This feature was a handy tool for both cadet and senior staff alike to quickly see who was considering leaving the program.

[This ticket was created to capture a historical user request. Feature re-implemented as of October 3, 2023.]

**Comment by grioux-neo** [comment]
Fix incorporated on 10/3/2023
