### ISSUE TITLE
Disable execute buttons on account functions activation

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#388]
**Is your feature request related to a problem? Please describe.**
Users are able to submit multiple account creations, username requests, and password resets repeatedly.  

**Describe the solution you'd like**
Disable action button until page is refreshed or reloaded.

**Describe alternatives you've considered**
Educating users to not click the button repeatedly.

**Comment by r-a303931** [comment]
Fixed by #32a2467dd9f92640e5ff67553ac1d119646822b4
