### ISSUE TITLE
Make response statements on account functions activation more visible

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#389]
**Is your feature request related to a problem? Please describe.**
Users submit multiple account creations, username requests, and password resets repeatedly because the system allows them to do so and also because the page response upon action request is not sufficiently highlighted to indicate that system action request has been received and will be processed appropriately.

**Describe the solution you'd like**
Make response page indicate request acceptance and next step action and timing explicit, such as "an email will be delivered to the primary address indicated in eServices.  If you do not see the email within 5 minutes of request activation, please check your spam folder...." etc.

**Describe alternatives you've considered**
Educating users to read the full web page.

**Comment by r-a303931** [comment]
Fixed by #394
