### ISSUE TITLE
Dynamic CAPF 60-80 generation link is unresponsive

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#40]
**Describe the bug**
CAPF 60-80 dynamic fillable form generation does not produce the expected results.  The link appears to be unresponsive.  Behavior reproduced on Arundel and St. Mary's calendar events.

**To Reproduce**
1. Go to calendar event with CAPF 60-80 identified
2. Click on CAPF 60-80

**Expected behavior**
Open a new tab with the dynamic pdf document in it

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Vivaldi

**Comment by r-a303931** [comment]
This was a configuration error with a specific build. No code changes are required, just verifying the next production build includes the correct configuration.
