### ISSUE TITLE
Event 'Move' does not always move an event

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#42]
**Describe the bug**

**To Reproduce**
1. Go to mdwg-28
2. Sign in 
3. Click on 'Move event'
4. Select 3 Oct
5. Refreshed display shows 3 Oct
6. Check calendar, event still on 17 Oct
Network shows 500 internal server error ("Could not update google calendar")

**Expected behavior**
Event should move to 3 Oct

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Vivaldi and Firefox, same behavior

**Comment by r-a303931** [comment]
Event update will be fixed with the next website update.
