### ISSUE TITLE
Incorporate automated CAPWATCH download functionality

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#88]
**Is your feature request related to a problem? Please describe.**
Incorporate nightly CAPWATCH file download and import functionality

**Describe the solution you'd like**
Incorporate nightly CAPWATCH file download and import functionality

**Comment by r-a303931** [comment]
This is a product of the environment and not something within the scope of this repository.

For example, automated Discord reminders. The framework is there to allow it to happen as part of the repository, but it is not something that can be done globally easily; rather, it is something that is done via a cron job.

The cron job method will work fine in this case, as [importCapwatch.ts](https://github.com/cap-md089/evmplus-v6/blob/master/packages/util-cli/src/importCapwatch.ts) provides the interface required for this feature.
