### ISSUE TITLE
The system is allowing more than one attendance record per member per event

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#91]
**Describe the bug**
Somehow the system is allowing more than one attendance record per event

**To Reproduce**
1. Go to mdwg event 31
2. Sign in
3. See duplicate attendance records

**Expected behavior**
There should be only one attendance record per member per event

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Vivaldi

**Comment by r-a303931** [comment]
FIxed in #bb2d8a1a3532aa6ae6620c41387bbc98c5a690fd
